runtime: nodejs20
#service: default

handlers:
  # Serve JavaScript files with correct MIME type
  - url: /(.*\.js)
    static_files: dist/portfolio/\1
    upload: dist/portfolio/(.*\.js)
    mime_type: application/javascript

  # Serve CSS files
  - url: /(.*\.css)
    static_files: dist/portfolio/\1
    upload: dist/portfolio/(.*\.css)
    mime_type: text/css

  # Serve JSON files with revalidation (avoid stale content after deploy)
  - url: /(.*\.json)
    static_files: dist/portfolio/\1
    upload: dist/portfolio/(.*\.json)
    secure: always
    http_headers:
      Cache-Control: "no-cache, max-age=0, must-revalidate"

  # Anything under /assets/... is a real file, serve it as-is
  - url: /(assets/.*)
    static_files: dist/portfolio/\1
    upload: dist/portfolio/assets/.*
    secure: always
    http_headers:
      Cache-Control: "public, max-age=31536000, immutable"

  # Serve images and other assets
  - url: /(.*\.(png|jpg|jpeg|gif|svg|ico|webp))
    static_files: dist/portfolio/\1
    upload: dist/portfolio/(.*\.(png|jpg|jpeg|gif|svg|ico|webp))

  # Catch-all handler to serve index.html for SPA routing
  - url: /.*
    static_files: dist/portfolio/index.html
    upload: dist/portfolio/index.html
